/*
 * Hand-crafted autoconf.h for ESP32-S3 (xtensa-esp32s3-elf-gcc)
 * Normally generated by tools/configure — we bypass that for ESP-IDF.
 */
#ifndef __BUILD_AUTOCONF_H
#define __BUILD_AUTOCONF_H

/* Architecture — Xtensa has no Rockbox arch enum, use "none" */
#define arch_none 0
#define arch_arm  1
#define arch_mips 2
#define arch_sh   3
#define ARCH_NONE 0
#define ARCH_ARM  1
#define ARCH_MIPS 2
#define ARCH_SH   3
#define ARCH arch_none

/* Endianness — ESP32-S3 is little-endian */
#define ROCKBOX_LITTLE_ENDIAN 1
#undef  ROCKBOX_BIG_ENDIAN

/* xtensa-esp32s3-elf-gcc 15.2 */
#define GCCNUM 150200

/* Application (hosted) platform — guard against redefinition from -DAPPLICATION */
#ifndef APPLICATION
#define APPLICATION
#endif

/* Define so that config.h includes config/esp32.h */
#define MODEL_HEADER "config/esp32.h"

#endif /* __BUILD_AUTOCONF_H */
