/* lang_core.c — stub for ESP32 port (normally generated by genlang) */
#include "lang.h"

unsigned char *language_strings[LANG_LAST_STRING_PLACEHOLDER];
const unsigned char core_language_builtin[] = { 0 };
