/*
 * rbversion.h — stub for ESP32 port.
 * Normally generated by the build system from version info.
 */
#ifndef _RBVERSION_H_
#define _RBVERSION_H_

#define RB_GIT_SHA1    "esp32-port"
#define RBVERSION      "ESP32-DEV"
#define RB_VERSION     "ESP32-DEV"
#define RB_BUILD_DATE  "2026-03-17"

#endif /* _RBVERSION_H_ */
