/*
 * sysfont.h — stub for ESP32 port.
 * Normally generated by convbdf from tools/. Provides the built-in system font.
 */
#ifndef _SYSFONT_H_
#define _SYSFONT_H_

#include "font.h"

/* Dimensions of the system font (matches Rockbox's built-in 08-Schumacher-Clean) */
#define SYSFONT_WIDTH  6
#define SYSFONT_HEIGHT 8

/* The system font bitmap data — provided by sysfont.c (also a stub) */
extern struct font sysfont;

#endif /* _SYSFONT_H_ */
