/*
 * sysfont.c — stub for ESP32 port.
 * Normally generated by convbdf from unifont.bdf.
 */
#include "font.h"

/* Minimal 1x1 placeholder glyph table */
static unsigned char sysfont_bits[] = { 0x00 };
static unsigned short sysfont_offset[] = { 0 };
static unsigned char sysfont_width[] = { 6 };

struct font sysfont = {
    .height   = 8,
    .ascent   = 6,
    .depth    = 0,
    .firstchar = 0x20,
    .size     = 1,
    .bits     = sysfont_bits,
    .offset   = sysfont_offset,
    .width    = sysfont_width,
    .defaultchar = 0x20,
    .maxwidth = 6,
};
